"""add recipient and phone to addresses

Revision ID: 2e29a2cefc04
Revises: 128eddf16966
Create Date: 2026-09-15 17:20:10.163275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e29a2cefc04'
down_revision: Union[str, Sequence[str], None] = '128eddf16966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('recipient_name', sa.String(length=150), nullable=False))
    op.add_column('address', sa.Column('phone_number', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'phone_number')
    op.drop_column('address', 'recipient_name')
    # ### end Alembic commands ###
