"""add object key to product image

Revision ID: 30ff76cb13a7
Revises: af1357e46b44
Create Date: 2026-09-16 12:51:54.419782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ff76cb13a7'
down_revision: Union[str, Sequence[str], None] = 'af1357e46b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('object_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_image', 'object_key')
    # ### end Alembic commands ###
