"""add order reservation expiration

Revision ID: 8b1a8d60a459
Revises: 0e301cb01a83
Create Date: 2026-09-15 17:29:24.149280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1a8d60a459'
down_revision: Union[str, Sequence[str], None] = '0e301cb01a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_order', sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_shop_order_reservation_expires_at'), 'shop_order', ['reservation_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_order_reservation_expires_at'), table_name='shop_order')
    op.drop_column('shop_order', 'reservation_expires_at')
    # ### end Alembic commands ###
