"""initial schema

Revision ID: af5a85f219b6
Revises: 
Create Date: 2026-09-15 16:19:17.389639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5a85f219b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payment_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_table('payment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='ux_category_name_parent'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_category_parent_id'), 'product_category', ['parent_id'], unique=False)
    op.create_table('promotion',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_type IN ('percentage', 'fixed')", name='ck_promotion_discount_type'),
    sa.CheckConstraint('discount_value >= 0', name='ck_promotion_discount_value'),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_promotion_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shipping_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_days', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_user_email'), 'site_user', ['email'], unique=True)
    op.create_table('variation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_is_active'), 'product', ['is_active'], unique=False)
    op.create_table('promotion_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'category_id', name='ux_promotion_category')
    )
    op.create_index(op.f('ix_promotion_category_category_id'), 'promotion_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_promotion_category_promotion_id'), 'promotion_category', ['promotion_id'], unique=False)
    op.create_table('shop_order',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_number', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KRW', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_method.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['site_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_order_number'), 'shop_order', ['order_number'], unique=True)
    op.create_index(op.f('ix_shop_order_status_id'), 'shop_order', ['status_id'], unique=False)
    op.create_index(op.f('ix_shop_order_user_id'), 'shop_order', ['user_id'], unique=False)
    op.create_table('shopping_cart',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['site_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_cart_user_id'), 'shopping_cart', ['user_id'], unique=True)
    op.create_table('user_address',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['site_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'address_id', name='uq_user_address')
    )
    op.create_index(op.f('ix_user_address_user_id'), 'user_address', ['user_id'], unique=False)
    op.create_table('user_payment_method',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_type_id', sa.Integer(), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['site_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_payment_method_id', name='uq_user_provider_payment_method')
    )
    op.create_index(op.f('ix_user_payment_method_user_id'), 'user_payment_method', ['user_id'], unique=False)
    op.create_table('variation_option',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('variation_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variation_id', 'value', name='ux_variation_option_value')
    )
    op.create_index(op.f('ix_variation_option_variation_id'), 'variation_option', ['variation_id'], unique=False)
    op.create_table('order_address',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_address_order_id'), 'order_address', ['order_id'], unique=False)
    op.create_table('order_payment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payment_type_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KRW', nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_order_payment_provider_id')
    )
    op.create_index(op.f('ix_order_payment_order_id'), 'order_payment', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_history_status_id'), 'order_status_history', ['status_id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_table('product_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_in_stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_product_item_price'),
    sa.CheckConstraint('qty_in_stock >= 0', name='ck_product_item_stock'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_item_is_active'), 'product_item', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_item_product_id'), 'product_item', ['product_id'], unique=False)
    op.create_table('inventory_movement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_item_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movement_order_id'), 'inventory_movement', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_product_item_id'), 'inventory_movement', ['product_item_id'], unique=False)
    op.create_table('order_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_item_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_line_order_id'), 'order_line', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_line_product_item_id'), 'order_line', ['product_item_id'], unique=False)
    op.create_table('product_configuration',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_item_id', sa.UUID(), nullable=False),
    sa.Column('variation_option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_option_id'], ['variation_option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_item_id', 'variation_option_id', name='ux_product_configuration')
    )
    op.create_index(op.f('ix_product_configuration_variation_option_id'), 'product_configuration', ['variation_option_id'], unique=False)
    op.create_table('shopping_cart_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_cart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_item_id', name='ux_cart_product_item')
    )
    op.create_index(op.f('ix_shopping_cart_item_cart_id'), 'shopping_cart_item', ['cart_id'], unique=False)
    op.create_index(op.f('ix_shopping_cart_item_product_item_id'), 'shopping_cart_item', ['product_item_id'], unique=False)
    op.create_table('user_review',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_user_review_rating'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['site_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_line_id', name='ux_user_review_order_line')
    )
    op.create_index(op.f('ix_user_review_order_line_id'), 'user_review', ['order_line_id'], unique=False)
    op.create_index(op.f('ix_user_review_user_id'), 'user_review', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_review_user_id'), table_name='user_review')
    op.drop_index(op.f('ix_user_review_order_line_id'), table_name='user_review')
    op.drop_table('user_review')
    op.drop_index(op.f('ix_shopping_cart_item_product_item_id'), table_name='shopping_cart_item')
    op.drop_index(op.f('ix_shopping_cart_item_cart_id'), table_name='shopping_cart_item')
    op.drop_table('shopping_cart_item')
    op.drop_index(op.f('ix_product_configuration_variation_option_id'), table_name='product_configuration')
    op.drop_table('product_configuration')
    op.drop_index(op.f('ix_order_line_product_item_id'), table_name='order_line')
    op.drop_index(op.f('ix_order_line_order_id'), table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_inventory_movement_product_item_id'), table_name='inventory_movement')
    op.drop_index(op.f('ix_inventory_movement_order_id'), table_name='inventory_movement')
    op.drop_table('inventory_movement')
    op.drop_index(op.f('ix_product_item_product_id'), table_name='product_item')
    op.drop_index(op.f('ix_product_item_is_active'), table_name='product_item')
    op.drop_table('product_item')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_order_status_history_status_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_payment_order_id'), table_name='order_payment')
    op.drop_table('order_payment')
    op.drop_index(op.f('ix_order_address_order_id'), table_name='order_address')
    op.drop_table('order_address')
    op.drop_index(op.f('ix_variation_option_variation_id'), table_name='variation_option')
    op.drop_table('variation_option')
    op.drop_index(op.f('ix_user_payment_method_user_id'), table_name='user_payment_method')
    op.drop_table('user_payment_method')
    op.drop_index(op.f('ix_user_address_user_id'), table_name='user_address')
    op.drop_table('user_address')
    op.drop_index(op.f('ix_shopping_cart_user_id'), table_name='shopping_cart')
    op.drop_table('shopping_cart')
    op.drop_index(op.f('ix_shop_order_user_id'), table_name='shop_order')
    op.drop_index(op.f('ix_shop_order_status_id'), table_name='shop_order')
    op.drop_index(op.f('ix_shop_order_order_number'), table_name='shop_order')
    op.drop_table('shop_order')
    op.drop_index(op.f('ix_promotion_category_promotion_id'), table_name='promotion_category')
    op.drop_index(op.f('ix_promotion_category_category_id'), table_name='promotion_category')
    op.drop_table('promotion_category')
    op.drop_index(op.f('ix_product_is_active'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('variation')
    op.drop_index(op.f('ix_site_user_email'), table_name='site_user')
    op.drop_table('site_user')
    op.drop_table('shipping_method')
    op.drop_table('promotion')
    op.drop_index(op.f('ix_product_category_parent_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_table('payment_type')
    op.drop_table('payment_event')
    op.drop_table('order_status')
    op.drop_table('address')
    # ### end Alembic commands ###
